{{- if .Values.istio.enabled -}}
{{- $fullName := include "spin-kub-helm-demo.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  {{- range .Values.virtualservice.hosts }}
  - {{ . }}
  {{- end }}
  gateways:
  {{- range .Values.virtualservice.gateways }}
  - {{ . }}
  {{- end }}
  http:
  - match:
    route:
    - destination:
        host: {{ $fullName }}
        port:
          number: 80

{{- end }}